### ISSUE TITLE
Prevent adding new test case if students are still creating one

### ISSUE THREAD

**Issue by chensivan** [LittleAprilFool/puzzlemi#39]
Shouldn't have more than one test case that are under creation.

![image](https://user-images.githubusercontent.com/2650733/74556987-2e789b00-4f2d-11ea-8071-b1f06a429556.png)

**Comment by soney** [comment]
Does https://github.com/LittleAprilFool/puzzlemi/issues/39 supersede this issue?

**Comment by chensivan** [comment]
THIS IS 39
